### ISSUE TITLE
Не запускается из-за перекрытия модуля features

### ISSUE THREAD

**Issue by midyukov-anton** [nucleron/IDE#1]
Столкнулся со следующей проблемой. yaplcide.py не стартует, так как 
import features
импортирует вместо ../beremiz/features.py другой файл: /usr/lib64/python2.7/site-packages/PIL/features.py
Этот модуль PIL/features.py обладает большим приоритетом при импортировании.
От этого модуля PIL зависит ряд важных пакетов, поэтому так просто его не удалишь.
Поэтому желательно как-то по другому импортировать ../beremiz/features.py, чтоб приоритет был выше у него.

**Comment by nucleron** [comment]
А "ванильный" Beremiz нормально запускается?

И да, какой дистрибутив(alt?)/версия?
Как ставится PIL?

**Comment by nucleron** [comment]
Попробуйте теперь.

**Comment by midyukov-anton** [comment]
> А "ванильный" Beremiz нормально запускается?

Да, нормально запускается. Так как features.py находится в том же каталоге, где и Beremiz.py, то приоритет выше у него, а не у глобального features.

> И да, какой дистрибутив(alt?)/версия?

ALT Linux Sisyphus. 

> Как ставится PIL?

Штатно, через пакетный менеджер, пакет python-module-pillow.

> Попробуйте теперь.

А теперь импортируется правильно и запускается. Спасибо. Проблема решена. Можно мержить в основную ветку.
